// <auto-generated />
namespace Task25.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddTegAndJoinToArticle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTegAndJoinToArticle));
        
        string IMigrationMetadata.Id
        {
            get { return "202011012323351_AddTegAndJoinToArticle"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
